// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"iot_device_simulation/internal/dao/internal"
)

// internalPublishInfoDao is internal type for wrapping internal DAO implements.
type internalPublishInfoDao = *internal.PublishInfoDao

// publishInfoDao is the data access object for table publish_info.
// You can define custom methods on it to extend its functionality as you wish.
type publishInfoDao struct {
	internalPublishInfoDao
}

var (
	// PublishInfo is globally public accessible object for table publish_info operations.
	PublishInfo = publishInfoDao{
		internal.NewPublishInfoDao(),
	}
)

// Fill with you ideas below.
