// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"iot_device_simulation/internal/dao/internal"
)

// internalSimulateDeviceDao is internal type for wrapping internal DAO implements.
type internalSimulateDeviceDao = *internal.SimulateDeviceDao

// simulateDeviceDao is the data access object for table simulate_device.
// You can define custom methods on it to extend its functionality as you wish.
type simulateDeviceDao struct {
	internalSimulateDeviceDao
}

var (
	// SimulateDevice is globally public accessible object for table simulate_device operations.
	SimulateDevice = simulateDeviceDao{
		internal.NewSimulateDeviceDao(),
	}
)

// Fill with you ideas below.
