// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"iot_device_simulation/internal/dao/internal"
)

// internalSubscribeInfoDao is internal type for wrapping internal DAO implements.
type internalSubscribeInfoDao = *internal.SubscribeInfoDao

// subscribeInfoDao is the data access object for table subscribe_info.
// You can define custom methods on it to extend its functionality as you wish.
type subscribeInfoDao struct {
	internalSubscribeInfoDao
}

var (
	// SubscribeInfo is globally public accessible object for table subscribe_info operations.
	SubscribeInfo = subscribeInfoDao{
		internal.NewSubscribeInfoDao(),
	}
)

// Fill with you ideas below.
