// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"iot_device_simulation/internal/dao/internal"
)

// internalTransducersDao is internal type for wrapping internal DAO implements.
type internalTransducersDao = *internal.TransducersDao

// transducersDao is the data access object for table transducers.
// You can define custom methods on it to extend its functionality as you wish.
type transducersDao struct {
	internalTransducersDao
}

var (
	// Transducers is globally public accessible object for table transducers operations.
	Transducers = transducersDao{
		internal.NewTransducersDao(),
	}
)

// Fill with you ideas below.
